package com.wellme.dto

data class UserDTO(var user_id : String?,
                   var phone : String?,
                   var first_name : String?,
                   var last_name : String?,
                   var fb_id : String?,
                   var google_id : String?,
                   var initial_logged_weight : String?,
                   var initial_logged_height : String?,
                   var age : String?,
                   var gender : String?,
                   var fitness_level : String?,
                   var waist : String?,
                   var hip : String?,
                   var neck : String?,
                   var refferal_code : String?,
                   var weight : String?,
                   var target_weight : String?,
                   var target_weight_time : String?,
                   var target_weight_type : String?,
                   var current_weight : String?,
                   var fat : String?,
                   var user_type : String?,
                   var city : String?,
                   var state : String?,
                   var country : String?,
                   var lattitude : String?,
                   var longitude : String?,
                   var app_version : String?,
                   var notification_id : String?,
                   var device_id : String?,
                   var coach_id : String?,
                   var coach_first_name : String?,
                   var coach_last_name : String?,
                   var medical_condition_id : String?,
                   var medical_condition : String?,
                   var goal_id : String?,
                   var goals : String?,
                   var occupation_id : String?,
                   var occupation : String?,
                   var added_on : String?,
                   var updated_on : String?,
                   var profile_image : String?,
                   var diet_preference : String?,
                   var allergies : String?,
                   var fitness_purpose : String?,
                   var preference_cuisine : String?,
                   var body_fat : String?,
                   var calf: String?,
                   var chest : String?,
                   var arm_left : String?,
                   var arm_reght : String?,
                   var thigh : String?,
                   var bio : String?,
                   var muscle_mass : String?,
                   var end_date : String?,
                   var fitness_target : String?
                   ) {
}